import React, { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowRight, Bell, BriefcaseBusiness, Check, ChevronDown, CircleDollarSign, Clock3, Code2, Compass, FolderKanban, Heart, LayoutDashboard, MessageCircle, Plus, Search, Send, Sparkles, Star, Users, X } from 'lucide-react'
import './styles.css'

type Role = 'client' | 'freelancer'
type Freelancer = { id:number; name:string; title:string; rate:string; avatar:string; skills:string[]; rating:number; reviews:number; available:boolean; bio:string; color:string }
type Project = { id:number; title:string; client:string; budget:string; duration:string; skills:string[]; description:string; posted:string; applicants:number }

const freelancers: Freelancer[] = [
 {id:1,name:'Maya Chen',title:'Product designer & researcher',rate:'$65/hr',avatar:'MC',skills:['Product design','Figma','Research'],rating:4.9,reviews:28,available:true,bio:'I turn complex products into calm, useful experiences. Formerly at two YC startups.',color:'#b8e5d0'},
 {id:2,name:'Alex Rivera',title:'Full-stack developer',rate:'$80/hr',avatar:'AR',skills:['React','Node.js','TypeScript'],rating:5,reviews:41,available:true,bio:'Shipping reliable products from first commit to launch day. Fast feedback, no surprises.',color:'#ffcf92'},
 {id:3,name:'Priya Nair',title:'Brand strategist & copywriter',rate:'$55/hr',avatar:'PN',skills:['Branding','Copywriting','Strategy'],rating:4.8,reviews:19,available:false,bio:'I help early teams sound like themselves and stand out in a noisy market.',color:'#d8c7ff'},
 {id:4,name:'Jordan Kim',title:'Motion designer',rate:'$70/hr',avatar:'JK',skills:['Motion','After Effects','3D'],rating:4.9,reviews:13,available:true,bio:'Making brands move with sharp, memorable visual systems and a little joy.',color:'#ffc4d6'},
]
const starterProjects: Project[] = [
 {id:1,title:'Design a landing page for a climate startup',client:'Northstar Energy',budget:'$1,200 – $2,000',duration:'2–3 weeks',skills:['Product design','Figma'],description:'We need a confident, editorial landing page that makes our clean-energy software feel simple and exciting.',posted:'2h ago',applicants:6},
 {id:2,title:'Build an MVP dashboard in React',client:'Luma Labs',budget:'$3,000 – $5,000',duration:'4–6 weeks',skills:['React','TypeScript','Node.js'],description:'Turn our workflows into a focused internal dashboard. API spec and design system are ready to go.',posted:'5h ago',applicants:12},
 {id:3,title:'Brand voice for a new wellness app',client:'Serein',budget:'$800 – $1,200',duration:'1–2 weeks',skills:['Branding','Copywriting'],description:'Name, tone, and a lightweight messaging guide for a softer kind of wellness product.',posted:'1d ago',applicants:4},
]
const seededMessages = [{from:'them',text:'Hey Maya — loved your work on the onboarding flow.',time:'10:42 AM'},{from:'me',text:'Thank you! I’d love to hear more about what you’re building.',time:'10:44 AM'}]

function App(){
 const [role,setRole]=useState<Role|null>(localStorage.getItem('role') as Role|null)
 const [user,setUser]=useState(localStorage.getItem('name')||'')
 const [view,setView]=useState('home'); const [query,setQuery]=useState(''); const [selected,setSelected]=useState<Freelancer|null>(null)
 const [projects,setProjects]=useState<Project[]>(()=>{try{return JSON.parse(localStorage.getItem('projects')||'null')||starterProjects}catch{return starterProjects}})
 const [chat,setChat]=useState(seededMessages); const [message,setMessage]=useState(''); const [showPost,setShowPost]=useState(false); const [toast,setToast]=useState(''); const [showWorkspace,setShowWorkspace]=useState(false)
 const enter=(r:Role)=>{setRole(r);localStorage.setItem('role',r);setView('dashboard')}
 const logout=()=>{localStorage.clear();setRole(null);setUser('');setView('home')}
 const filtered=useMemo(()=>freelancers.filter(f=>[f.name,f.title,...f.skills].join(' ').toLowerCase().includes(query.toLowerCase())),[query])
 if(!role) return <Landing onEnter={enter} />
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><span className="brand-mark">✦</span><span>freelance</span></div><div className="workspace-wrap"><button className="workspace" onClick={()=>setShowWorkspace(!showWorkspace)}><div className="user-dot">{user?user.slice(0,2).toUpperCase():'YO'}</div><div><b>{user||'Your workspace'}</b><small>{role==='client'?'Client account':'Freelancer account'}</small></div><ChevronDown size={15}/></button>{showWorkspace&&<div className="workspace-menu"><b>Switch workspace</b><button onClick={()=>{setRole('client');localStorage.setItem('role','client');setView('dashboard');setShowWorkspace(false)}}><BriefcaseBusiness size={15}/> Client view</button><button onClick={()=>{setRole('freelancer');localStorage.setItem('role','freelancer');setView('dashboard');setShowWorkspace(false)}}><Users size={15}/> Freelancer view</button></div>}</div><nav>{[['dashboard',LayoutDashboard,'Overview'],['discover',Compass,role==='client'?'Find talent':'Find work'],['messages',MessageCircle,'Messages'],['profile',Users,'My profile']].map(([key,Icon,label])=><button key={key as string} className={view===key?'active':''} onClick={()=>setView(key as string)}><Icon size={18}/>{label as string}{key==='messages'&&<i>2</i>}</button>)}</nav><div className="sidebar-bottom"><div className="pro-card"><Sparkles size={17}/><b>Make your profile shine</b><p>Add work samples to get 3× more replies.</p><button onClick={()=>setView('profile')}>Complete profile <ArrowRight size={14}/></button></div><button className="logout" onClick={logout}>Log out</button></div></aside>
  <main className="main"><header><div className="breadcrumbs"><span>Workspace</span><b>/</b><strong>{view==='dashboard'?'Overview':view==='discover'?(role==='client'?'Find talent':'Find work'):view[0].toUpperCase()+view.slice(1)}</strong></div><div className="header-actions"><button className="icon-btn" onClick={()=>setToast('You have 2 new notifications')}><Bell size={18}/><i></i></button><div className="mini-avatar">{user?user.slice(0,2).toUpperCase():'YO'}</div></div></header>
   {view==='dashboard'&&<Dashboard role={role} projects={projects} onDiscover={()=>setView('discover')} onPost={()=>setShowPost(true)} onSelect={setSelected} />}
   {view==='discover'&&<Discover role={role} query={query} setQuery={setQuery} freelancers={filtered} projects={projects} onSelect={setSelected} onPost={()=>setShowPost(true)} />}
   {view==='messages'&&<Messages chat={chat} message={message} setMessage={setMessage} onSend={()=>{if(message.trim()){setChat([...chat,{from:'me',text:message,time:'now'}]);setMessage('')}}} />}
   {view==='profile'&&<Profile role={role} user={user} setUser={setUser} onSave={()=>{localStorage.setItem('name',user);setToast('Profile saved ✓')}} onToast={setToast} />}
  </main>
  {selected&&<ProfileModal f={selected} onClose={()=>setSelected(null)} onMessage={()=>{setSelected(null);setView('messages');setToast('Conversation started')}} />}
  {showPost&&<PostModal onClose={()=>setShowPost(false)} onPost={(p)=>{const next=[{...p,id:Date.now(),client:user||'You',posted:'just now',applicants:0},...projects];setProjects(next);localStorage.setItem('projects',JSON.stringify(next));setShowPost(false);setToast('Project posted — matched talent is on the way!')}} />}
  {toast&&<div className="toast"><Check size={16}/>{toast}<button onClick={()=>setToast('')}><X size={14}/></button></div>}
 </div>
}
function Landing({onEnter}:{onEnter:(r:Role)=>void}){const [name,setName]=useState('');return <div className="landing"><div className="landing-nav"><div className="brand light"><span className="brand-mark">✦</span> freelance</div><span className="nav-note">The human side of getting work done.</span></div><section className="hero"><div className="hero-copy"><div className="eyebrow"><span>✳</span> A better way to freelance</div><h1>Good work finds<br/><em>good people.</em></h1><p>Freelance connects ambitious clients with independent talent — without the noise, guesswork, or endless applications.</p><div className="signup"><input placeholder="Your name" value={name} onChange={e=>setName(e.target.value)}/><button onClick={()=>{if(name)localStorage.setItem('name',name);onEnter('freelancer')}}>Get started <ArrowRight size={17}/></button></div><div className="role-links"><span>I'm here to</span><button onClick={()=>onEnter('freelancer')}>Find great work</button><b>or</b><button onClick={()=>onEnter('client')}>Hire great people</button></div></div><div className="hero-art"><div className="orbit orbit-one"></div><div className="orbit orbit-two"></div><div className="art-card card-main"><div className="art-top"><span className="status-dot"></span>New project match</div><h3>Brand identity for<br/>a kinder internet</h3><div className="art-tags"><span>Branding</span><span>Strategy</span></div><div className="art-person"><div className="person-pic">PN</div><div><b>Priya Nair</b><small>Brand strategist</small></div><strong>98% match</strong></div></div><div className="float-note note-one"><Star size={14} fill="currentColor"/> 5.0 <small>from 41 clients</small></div><div className="float-note note-two"><span>↗</span> 12 new projects <small>this week</small></div><div className="blob"></div></div></section><footer><span>Trusted by independent talent at every stage.</span><div><span className="trusted">○ notion</span><span className="trusted">◒ Vercel</span><span className="trusted">▰ linear</span></div></footer></div>}
function Dashboard({role,projects,onDiscover,onPost,onSelect}:{role:Role;projects:Project[];onDiscover:()=>void;onPost:()=>void;onSelect:(f:Freelancer)=>void}){return <div className="content"><div className="page-title"><div><div className="eyebrow">{role==='client'?'TUESDAY, SEPTEMBER 17':'TUESDAY, SEPTEMBER 17'}</div><h2>{role==='client'?'Find your next great hire.':'Make space for work you love.'}</h2><p>{role==='client'?'A shortlist of people who can make your next project happen.':'Curated opportunities, matched to your skills and ambitions.'}</p></div><button className="primary" onClick={role==='client'?onPost:onDiscover}>{role==='client'?<><Plus size={17}/> Post a project</>:<>Explore projects <ArrowRight size={16}/></>}</button></div><div className="stats"><div><span>Active {role==='client'?'projects':'applications'}</span><b>{role==='client'?'04':'08'}</b><small className="up">↗ 18% this month</small></div><div><span>New matches</span><b>{role==='client'?'12':'14'}</b><small>Since last week</small></div><div><span>Profile views</span><b>{role==='client'?'238':'186'}</b><small className="up">↗ 24% this month</small></div></div>{role==='client'?<><div className="section-head"><h3>Recommended for your projects <span className="count">12</span></h3><button onClick={onDiscover}>View all <ArrowRight size={15}/></button></div><div className="talent-grid">{freelancers.slice(0,3).map(f=><TalentCard key={f.id} f={f} onSelect={onSelect}/>)}</div></>:<><div className="section-head"><h3>Projects that fit your skills <span className="count">14</span></h3><button onClick={onDiscover}>View all <ArrowRight size={15}/></button></div><div className="project-list">{projects.slice(0,2).map(p=><ProjectCard key={p.id} p={p}/>)}</div></>}<div className="below-grid"><div><div className="section-head"><h3>{role==='client'?'Your active projects':'Your recent activity'}</h3><button onClick={onDiscover}>See all <ArrowRight size={15}/></button></div><div className="activity-card">{role==='client'?projects.slice(0,3).map(p=><div className="activity-row" key={p.id}><div className="activity-icon"><FolderKanban size={16}/></div><div><b>{p.title}</b><small>{p.client} · {p.budget}</small></div><span className="pill green">Active</span></div>):<div className="activity-row"><div className="activity-icon"><Check size={16}/></div><div><b>Profile is 82% complete</b><small>Add 2 work samples to stand out</small></div><button className="text-button" onClick={onDiscover}>Finish profile</button></div>}</div></div><div className="tip"><div className="tip-icon">✦</div><b>Small steps, big momentum.</b><p>People who reply within 24 hours are 2× more likely to get hired.</p><button onClick={()=>onDiscover()}>View your inbox <ArrowRight size={14}/></button></div></div></div>}
function TalentCard({f,onSelect}:{f:Freelancer;onSelect:(f:Freelancer)=>void}){return <article className="talent-card"><div className="card-cover" style={{background:f.color}}><span className="availability">{f.available?'Available now':'In a project'}</span><div className="big-avatar">{f.avatar}</div></div><div className="talent-body"><div className="name-row"><div><h4>{f.name}</h4><p>{f.title}</p></div><button className="heart" onClick={()=>alert('Saved to your shortlist')}><Heart size={17}/></button></div><div className="skill-row">{f.skills.slice(0,2).map(s=><span key={s}>{s}</span>)}</div><div className="rating"><Star size={14} fill="currentColor"/> {f.rating} <small>({f.reviews})</small><b>{f.rate}</b></div><button className="outline full" onClick={()=>onSelect(f)}>View profile</button></div></article>}
function ProjectCard({p}:{p:Project}){const [applied,setApplied]=useState(false);return <article className="project-card"><div className="project-icon"><Code2 size={19}/></div><div className="project-main"><div className="project-meta"><span>{p.posted}</span><span>·</span><span>{p.applicants} applicants</span></div><h4>{p.title}</h4><p>{p.description}</p><div className="skill-row">{p.skills.map(s=><span key={s}>{s}</span>)}</div></div><div className="project-side"><b>{p.budget}</b><small><Clock3 size={13}/> {p.duration}</small><button className="outline" onClick={()=>setApplied(!applied)}>{applied?'Applied ✓':'View project'}</button></div></article>}
function Discover({role,query,setQuery,freelancers,projects,onSelect,onPost}:{role:Role;query:string;setQuery:(s:string)=>void;freelancers:Freelancer[];projects:Project[];onSelect:(f:Freelancer)=>void;onPost:()=>void}){return <div className="content"><div className="page-title compact"><div><div className="eyebrow">DISCOVER</div><h2>{role==='client'?'People who get it.':'Work worth doing.'}</h2><p>{role==='client'?'Search by skill, experience, or just a feeling.':'Projects from thoughtful clients looking for independent talent.'}</p></div>{role==='client'&&<button className="primary" onClick={onPost}><Plus size={17}/> Post a project</button>}</div><div className="search-row"><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={role==='client'?'Search people or skills':'Search projects or skills'}/></div><button className="filter" onClick={()=>alert('Category filters are ready for your search')}>All categories <ChevronDown size={15}/></button><button className="filter" onClick={()=>alert('Showing the best matches first')}>Best match <ChevronDown size={15}/></button></div>{role==='client'?<div className="talent-grid discover-grid">{freelancers.map(f=><TalentCard key={f.id} f={f} onSelect={onSelect}/>)}</div>:<div className="project-list">{projects.filter(p=>[p.title,p.client,...p.skills].join(' ').toLowerCase().includes(query.toLowerCase())).map(p=><ProjectCard key={p.id} p={p}/>)}</div>}</div>}
function Messages({chat,message,setMessage,onSend}:{chat:{from:string;text:string;time:string}[];message:string;setMessage:(s:string)=>void;onSend:()=>void}){return <div className="content"><div className="page-title compact"><div><div className="eyebrow">MESSAGES</div><h2>Keep the good work moving.</h2><p>Conversations with your clients and collaborators.</p></div></div><div className="messages-layout"><div className="conversation-list"><div className="search"><Search size={16}/><input placeholder="Search conversations"/></div><div className="conversation selected"><div className="person-pic">MC</div><div><b>Maya Chen</b><small>Looking forward to it!</small></div><time>10:44</time></div><div className="conversation"><div className="person-pic orange">AR</div><div><b>Alex Rivera</b><small>Project details attached</small></div><time>Mon</time></div></div><div className="chat-panel"><div className="chat-head"><div className="person-pic">MC</div><div><b>Maya Chen</b><small><span className="online"></span> Online · Product designer</small></div><button className="icon-btn"><MoreDots/></button></div><div className="chat-body">{chat.map((m,i)=><div className={'bubble-row '+m.from} key={i}><div className="bubble">{m.text}<small>{m.time}</small></div></div>)}<div className="project-share"><div className="share-icon"><BriefcaseBusiness size={17}/></div><div><small>PROJECT DISCUSSION</small><b>Design a landing page for Northstar</b></div><ArrowRight size={16}/></div></div><div className="composer"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==='Enter'&&onSend()} placeholder="Write a message..."/><button onClick={onSend}><Send size={16}/></button></div></div></div></div>}
const MoreDots=()=> <span className="dots">•••</span>
function Profile({role,user,setUser,onSave,onToast}:{role:Role;user:string;setUser:(s:string)=>void;onSave:()=>void;onToast:(s:string)=>void}){
 const [headline,setHeadline]=useState(localStorage.getItem('headline')|| (role==='client'?'Founder at your company':'Independent designer & builder'));
 const [about,setAbout]=useState(localStorage.getItem('about')||'I care about thoughtful work, clear communication, and making things people actually want to use.');
 const [skills,setSkills]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem('skills')||'null')||['Product design','Figma']}catch{return ['Product design','Figma']}});
 const [skillInput,setSkillInput]=useState('');
 const [editingCover,setEditingCover]=useState(false);
 const addSkill=()=>{const value=skillInput.trim();if(value&&!skills.some(s=>s.toLowerCase()===value.toLowerCase())){setSkills([...skills,value]);setSkillInput('')}};
 const save=()=>{localStorage.setItem('name',user);localStorage.setItem('headline',headline);localStorage.setItem('about',about);localStorage.setItem('skills',JSON.stringify(skills));onSave()};
 return <div className="content"><div className="page-title compact"><div><div className="eyebrow">YOUR PROFILE</div><h2>Let your work speak.</h2><p>A clear profile helps the right people find you.</p></div><button className="primary" onClick={save}><Check size={17}/> Save changes</button></div><div className="profile-editor"><div className="profile-preview"><div className="profile-cover" onClick={()=>setEditingCover(!editingCover)}><button className="cover-edit" onClick={(e)=>{e.stopPropagation();setEditingCover(true)}}>✎ Edit cover</button></div><div className="profile-avatar">{user?user.slice(0,2).toUpperCase():'YO'}</div><h3>{user||'Your name'}</h3><p>{headline}</p><div className="profile-rating"><Star size={15} fill="currentColor"/> New profile · <span>Complete {Math.min(100,60+skills.length*5)}%</span></div>{editingCover&&<div className="cover-swatches"><button onClick={()=>document.documentElement.style.setProperty('--profile-cover','linear-gradient(135deg,#b8e5d0,#d8c7ff)')}></button><button onClick={()=>document.documentElement.style.setProperty('--profile-cover','linear-gradient(135deg,#ffcf92,#ffc4d6)')}></button><button onClick={()=>document.documentElement.style.setProperty('--profile-cover','linear-gradient(135deg,#d8c7ff,#b8e5d0)')}></button></div>}</div><div className="form-card"><label>Display name<input value={user} onChange={e=>setUser(e.target.value)} placeholder="Your name"/></label><label>Headline<input value={headline} onChange={e=>setHeadline(e.target.value)} placeholder="What do you do?"/></label><label>About you<textarea value={about} onChange={e=>setAbout(e.target.value)} placeholder="Tell people what makes your work different..."/></label><div className="form-section"><b>{role==='client'?'What are you looking for?':'Your skills'}</b><div className="skill-row editable">{skills.map(skill=><span key={skill}>{skill}<button aria-label={'Remove '+skill} onClick={()=>setSkills(skills.filter(s=>s!==skill))}><X size={12}/></button></span>)}{skills.length===0&&<small className="empty-skills">Add your first skill below</small>}</div><div className="skill-input"><input value={skillInput} onChange={e=>setSkillInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addSkill()} placeholder="e.g. User research, React, Copywriting"/><button className="outline" onClick={addSkill}><Plus size={13}/> Add skill</button></div><small className="helper">Press Enter or click Add skill. Add as many as you like.</small></div><div className="form-section profile-options"><b>Profile settings</b><label className="check-row"><input type="checkbox" defaultChecked/> Show me as available for new work</label><label className="check-row"><input type="checkbox" defaultChecked/> Let clients discover my profile</label></div></div></div></div>}
function ProfileModal({f,onClose,onMessage}:{f:Freelancer;onClose:()=>void;onMessage:()=>void}){return <div className="overlay"><div className="modal profile-modal"><button className="close" onClick={onClose}><X/></button><div className="modal-cover" style={{background:f.color}}><div className="big-avatar">{f.avatar}</div></div><div className="modal-content"><div className="modal-title"><div><h2>{f.name}</h2><p>{f.title}</p></div><span className="available-label">● {f.available?'Available now':'Currently busy'}</span></div><div className="rating large"><Star size={16} fill="currentColor"/> {f.rating} <small>({f.reviews} reviews)</small><b>{f.rate}</b></div><p className="bio">{f.bio}</p><div className="skill-row">{f.skills.map(s=><span key={s}>{s}</span>)}</div><div className="modal-actions"><button className="outline" onClick={onClose}>Save for later</button><button className="primary" onClick={onMessage}><MessageCircle size={16}/> Start a conversation</button></div><div className="review"><div className="person-pic orange">AR</div><div><p>“Maya asked the right questions, then made the work feel effortless.”</p><small>Alex Rivera · Founder at Northstar</small></div></div></div></div></div>}
function PostModal({onClose,onPost}:{onClose:()=>void;onPost:(p:Omit<Project,'id'|'client'|'posted'|'applicants'>)=>void}){const [title,setTitle]=useState('');const [budget,setBudget]=useState('$1,000 – $2,000');const [skills,setSkills]=useState('Product design, Figma');return <div className="overlay"><div className="modal post-modal"><button className="close" onClick={onClose}><X/></button><div className="eyebrow">NEW PROJECT</div><h2>Tell the right people<br/><em>what you’re building.</em></h2><p className="modal-intro">Be specific, stay human. Great briefs attract great collaborators.</p><label>Project title<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Design a landing page for a climate startup"/></label><label>What do you need help with?<textarea placeholder="A few lines about the project, goals, and what success looks like."/></label><div className="two-fields"><label>Budget<input value={budget} onChange={e=>setBudget(e.target.value)}/></label><label>Duration<input defaultValue="2–3 weeks"/></label></div><label>Skills needed<input value={skills} onChange={e=>setSkills(e.target.value)}/></label><button className="primary full" disabled={!title} onClick={()=>onPost({title,budget,duration:'2–3 weeks',skills:skills.split(',').map(s=>s.trim()),description:'A new project looking for thoughtful independent talent.'})}>Post project <ArrowRight size={16}/></button></div></div>}

createRoot(document.getElementById('root')!).render(<App />)
